CREATE TABLE GRAPH (
	ID INTEGER NOT NULL PRIMARY KEY,
	CODE VARCHAR (128) NOT NULL,
	VERTEX INTEGER NOT NULL,
	EDGE INTEGER,
	EDGECON INTEGER
);
ALTER TABLE GRAPH ADD COLUMN vertcon INTEGER ;
ALTER TABLE GRAPH ADD COLUMN conn INTEGER ;
ALTER TABLE GRAPH ADD COLUMN radius INTEGER ;
ALTER TABLE GRAPH ADD COLUMN diametr INTEGER ;

ALTER TABLE GRAPH ADD COLUMN components INTEGER ;
ALTER TABLE GRAPH ADD COLUMN girth INTEGER ;
ALTER TABLE GRAPH ADD COLUMN primitive INTEGER ;
ALTER TABLE GRAPH ADD COLUMN exp INTEGER ;
ALTER TABLE GRAPH ADD COLUMN twoPartial INTEGER ;